use_wandb: true # if true, use wandb for recording
project: MSSegmentation # wandb project name
group: Base # a filter
# notes will show in wandb
notes: dummy

base_dir: ./data/isbi2015/
mri_type: flair
checkpoints: checkpoints
batch_size: 8
num_workers: 4
