model: unet # unet | atten-unet
num_epochs: 200 # total iteration steps

# -------------------------optimizer---------------------------

lr_policy: cosine # linear | step | cosine
lr: 0.005 # The learning rate of initialization
lr_beta1: 0.9 # adam optimizer's momentum
lr_beta2: 0.999 # adam optimizer's momentum

# -------------------------weights---------------------------

dice_weight: 3

# -------------------------network---------------------------

img_ch: 1 # The size of image channel
img_size: 128 # The size of image: H and W
features: [16, 32, 64, 128] # dropout ratios ues in ups and downs
dropout_ratios: [0.1, 0.1, 0.2, 0.2, 0.3] # dropout ratios ues in ups and downs
use_bn: true
