# -------------------------wandb-------------------------------
group: MaxViT # a filter
# notes will show in wandb
notes: dummy

# -------------------------model-------------------------------

batch_size: 32
mri_types: ["flair"]
model: maxvit-unet # unet | atten-unet | maxvit-unet
mbconv_expansion_rate: 2 # used in maxvit-unet
num_epochs: 300 # total iteration steps
img_ch: 1 # The size of image channel
img_size: 224 # The size of image: H and W
features: [16, 32, 64, 128] # dropout ratios ues in ups and downs
dropout_ratios: [0.1, 0.1, 0.2, 0.2, 0.3] # dropout ratios ues in ups and downs
use_bn: true
activation: elu

# -------------------------optimizer---------------------------

lr_policy: cosine # linear | step | cosine
lr_decay_freq: 100
gamma: 0.2
lr: 0.005 # The learning rate of initialization
lr_beta1: 0.9 # adam optimizer's momentum
lr_beta2: 0.999 # adam optimizer's momentum

# -------------------------weights---------------------------

dice_weight: 1.5
